spring.application.name=ResumeAnalyzer


//chat.model=llama3.2:3b

spring.datasource.url=jdbc:postgresql://localhost:5432/resume_ai
spring.datasource.username=poonam
spring.datasource.password=

spring.ai.vectorstore.pgvector.initialize-schema=true

server.port=8080
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.embedding.model=nomic-embed-text
//spring.ai.vectorstore.chroma.client.host=localhost
//spring.ai.vectorstore.chroma.client.port=8000

//spring.ai.vectorstore.chroma.client.base-url=http://localhost:8000